final/board/urls.py
from django.urls import path
from . import views

app_name ='board'

urlpatterns = [
    path('', views.BoardListView.as_view(), name='board_list'),
    path('post/<int:pk>/', views.post_detail_view, name='post_detail'),
    path('write/', views.post_write_view, name='post_write'),
    path('add_comment/<int:pk>', views.post_comment_add_view, name='add_comment')
]

final/final/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("trip.urls")),
    path('board/', include('board.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/trip_app/favicon.ico', permanent=True)),
    path('summernote/', include('django_summernote.urls')),
    path('', include('social_django.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/trip/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'trip'
urlpatterns = [

    # 메인페이지 by 영환
    path('search_trip/', views.search_trip, name='search_trip'),
    
    # 메인페이지 종료

    # 마이페이지 by 영환
    path('mypage/profile/', views.profile, name='profile'),
    path('mypage/post_detail/<int:post_id>', views.post_detail, name='post_detail'),
    path('mypage/mytopics/', views.mytopics, name='mytopics'),
    path('mypage/myfeadback/', views.myfeadback, name='myfeadback'),
    path('mypage/like_schedule/', views.like_schedule, name='like_schedule'),
    path('mypage/chatting_room/', views.chatting_room, name='chatting_room'),
    path('mypage/user_report/', views.user_report, name='user_report'),
    path('mypage/report_submit/', views.report_submit, name='report_submit'),
    path('mypage/view_report/', views.view_report, name='view_report'),
    path('mypage/view_user_report/<int:id>', views.view_user_report, name='view_user_report'),
    path('mypage/report_update/<int:id>', views.report_update, name='report_update'),
    
    # 관리자 페이지 by 영환
    path("admin_page/", views.admin_page, name="admin_page"),
    path("admin_page/admin_management", views.admin_management, name="admin_management"),
    path("admin_page/change_state/<str:username>", views.change_state, name="change_state"),
    path("admin_page/create_product", views.create_product, name="create_product"),
    path("admin_page/update_product/<int:package_id>", views.update_product, name="update_product"),
    path("admin_page/product_management", views.product_management, name="product_management"),
    path("admin_page/deleted_product", views.deleted_product, name="deleted_product"),
    path("admin_page/delete_cancel/<int:package_id>", views.delete_cancel, name="delete_cancel"),
    path("admin_page/order_inquiry", views.order_inquiry, name="order_inquiry"),
    path("admin_page/delivery_tracking", views.delivery_tracking, name="delivery_tracking"),
    path("admin_page/return_management", views.return_management, name="return_management"),
    path("admin_page/report_detail", views.report_detail, name="report_detail"),
    path("admin_page/view_report_detail/<int:id>", views.view_report_detail, name="view_report_detail"),
    path("admin_page/report_complete/<int:id>", views.report_complete, name="report_complete"),
    path("admin_page/blacklist_management", views.blacklist_management, name="blacklist_management"),
    path("admin_page/black_cancel/<int:blacklist_id>", views.black_cancel, name="black_cancel"),
    # 관리자 페이지 종료

    #by 건영
    path('',views.index, name = "index"),
    path('about/',views.about, name='about'),
    path('contact/',views.contact, name='contact'),
    path('elements/',views.elements, name='elements'),
    path('main/',views.main, name='main'),
    path('together_walk/',views.together_walk, name='together_walk'),
    path('add_comment/<int:id>/', views.add_comment, name='add_comment'),
    path('delete_comment/<int:id>/', views.delete_comment, name='delete_comment'),
  
    # 여행 상품 페이지 By 수현
    path('packages/',views.packages, name='packages'),
    path('packages/package_detail/<int:id>',views.package_detail, name='package_detail'),
    path('together_detail/<int:id>/',views.together_detail, name='together_detail'), 
    path('together_detail/',views.together_detail, name='together_detail'),

    # 위시리스트 추가 by 문정
    path('add_wishlist/<int:id>', views.add_wishlist, name='add_wishlist'),

    # 로그인, 회원가입 페이지 by 문정
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name= 'logout'),
    path('register/', views.register, name='register'),
    
    #CHATBOT BY 영민
    path('chatbot/', views.chatbot, name='chatbot'),
    path('chatapi/<str:question>', views.chatapi, name='chatapi'),
    
    #실시간 채팅 BY 영민
    path('chat/', views.chatting, name='chatting'),
    path('chat/<str:room_name>/', views.room, name='room'),
    path('test/', views.chat_test, name="chat_test"),
    path('check_room/<int:room_name>/<str:room_title>', views.check_room, name='check_room'),
    path('room_list', views.room_list, name='room_list'),

    #동행모집글 By 수현
    path('community/', views.community, name='community'),
    
    path('community_write/', views.community_write, name='community_write'),
    path('set_write/', views.set_write, name='set_write'),
    path('set_region/', views.set_region, name='set_region'),
    
    path('delete_write/', views.delete_write, name='delete_write'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/board/models.py
from django.db import models
from trip.models import User
# Create your models here.
class Post(models.Model):
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    review = models.PositiveBigIntegerField(verbose_name='조회수', default=0)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    top_fixed = models.BooleanField(verbose_name='상단고정', default=False)

    def __str__(self):
        return self.title

    class Meta:
        db_table = '게시판'
        verbose_name = '게시판'
        
class PostComment(models.Model):
    post_name = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment')
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    content = models.TextField(max_length=300, verbose_name='댓글내용')
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['-create_at']

final/board/forms.py
from django import forms
from .models import Post
from django_summernote.widgets import SummernoteWidget

class PostWriteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostWriteForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = '제목'
        self.fields['title'].widget.attrs.update({
            'placeholder': '제목을 입력해주세요.',
            'class': 'form-control form-title-input',
            'autofocus': True,
        })

    class Meta:
        model = Post
        fields = ['title', 'content']
        widgets = {
            'content': SummernoteWidget(),
        }

final/board/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from .models import Post, PostComment
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from .forms import PostWriteForm
from django.http import JsonResponse
from datetime import datetime
from django.core.serializers import serialize

class BoardListView(ListView):
    model = Post
    paginate_by = 10
    template_name = "boards/board_test.html"
    context_object_name = "post_list"
    
    def get_queryset(self):
        board_list = Post.objects.order_by('-id') 
        return board_list
    
    # 페이지네이션 오버라이딩
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        return context

def post_detail_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.review += 1
    post.save()
    comment = PostComment.objects.filter(post_name=post)
    current_time = datetime.now()
    context = {
        'post':post,
        'comment':comment,
        'current_time':current_time
    }
    return render(request, 'boards/post_test.html', context)

@login_required
def post_write_view(request):
    if request.method == 'POST':
        form = PostWriteForm(request.POST)
        user = request.user
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = user
            post.save()
            return redirect('board:board_list')
    else:
        form = PostWriteForm()          
    return render(request, 'boards/write.html', {'form':form})

def post_update_view(request):
    return

@login_required
def post_comment_add_view(request, pk):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=pk)
        content = request.POST.get('content')
        if len(content) <= 300 :
            obj= PostComment.objects.create(
                post_name = post,
                writer = request.user,
                content = content
            )
        
            current_time = datetime.now()
            
            serialized_obj = serialize('json', [obj])
            context = {
                'is_create': True,
                'comment':serialized_obj,
                'current_time':current_time            
            }
            print(current_time)
            print(obj.create_at)
            return JsonResponse(context)
    return JsonResponse({'is_create':False})

final/board/templates/boards/board.html
<div class="board-wrap">
    <div class="board-container">
        <table class="rwd-table">
            <thead>
                <tr class="text-center">
                    <th>번호</th>
                    <th>제목</th>
                    <th>작성자</th>
                    <th>등록일</th>
                    <th>조회수</th>
                </tr>
            </thead>
            <tbody>
                {% if post_list %}
                    {% for post in post_list %}
                    <tr class="text-center" style="cursor:pointer;" onclick = 'location.href="/board/post/{{post.id}}"'>
                        <td>{{ post.id }}</td>
                        <td class='post-title'>{{ post.title|truncatechars:30 }}</td>
                        <td>{{ post.writer }}</td>
                        <td>{{ post.create_at|date:'Y. m. d' }}</td>
                        <td>{{ post.review }}</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr class="text-center">
                        <td colspan="5">
                            작성된 게시글이 없습니다.
                        </td>
                    </tr>
                {% endif %}
            </tbody>
            
        </table>
        {% if user.is_authenticated %}
        <div class='btn-container'>
            <button id="write" class= 'btn btn-sm' onclick="window.location.href='{% url 'board:post_write' %}'">글쓰기</button>
        </div>
        {% endif %}

        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                        tabindex="-1">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">이전</a>
                </li>
                {% endif %}

                {% for page in page_range %}
                <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                    <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="p    age-item">
                    <a class="page-link"
                        href="?page={{ page_obj.next_page_number }}">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">다음</a>
                </li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
</div>

final/board/templates/boards/board_test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="manifest" href="site.webmanifest">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'boards/board.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin_vendor/fontawesome-free/css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/chatbot.css' %}">
</head>
<body>
    {% include 'nav.html' %}
    {% include 'boards/board.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
	<!-- JS here -->
	
		<!-- All JS Custom Plugins Link Here here -->
        <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
		
		<!-- Jquery, Popper, Bootstrap -->
		<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
	    <!-- Jquery Mobile Menu -->
        <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>

		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/slick.min.js' %}"></script>
		<!-- One Page, Animated-HeadLin -->
        <script src="{% static 'js/wow.min.js' %}"></script>
		<script src="{% static 'js/animated.headline.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

		<!-- Scrollup, nice-select, sticky -->
        <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
		<script src="{% static 'js/jquery.sticky.js' %}"></script>
        
        <!-- contact js -->
        <script src="{% static 'js/contact.js' %}"></script>
        <script src="{% static 'js/jquery.form.js' %}"></script>
        <script src="{% static 'js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        
		<!-- Jquery Plugins, main Jquery -->	
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

        <!-- ChatBot -->
        <script src="{% static 'js/chatbot.js' %}"></script>
</body>
</html>

final/board/templates/boards/post_detail.html
<div class="post-wrap">
    {% csrf_token %}
    <div class="post-container flex-center">
        <div class="flex-center card">
            <!--제목,분류,작성일-->
            <div class="card-header">
                <p><strong>{{ post.title }}</strong><span>[게시판]</span></p>
                <p><span>{{ post.create_at|date:'Y.m.d. H:i' }}</span></p>
            </div>
            <div class="card-body">
                <!--작성자, 조회수-->
                <div>
                    <span>작성자 : {{ post.writer }}</span>
                    <span>조회수 : {{ post.review }}</span>
                </div>
                <!--내용-->
                <div>
                    {{ post.content|safe }}
                </div>
                <div class='content-btn'>
                    <button id="write" class= 'btn btn-sm' onclick="location.href='/board/'">목록으로</button>
                </div>
            </div>
        </div>
        
    </div>
    <div class="post_comment">
        <div class="comment-header">
            <div class="comment-info">
                <p>댓글 {{ comment|length }} 개</p>
            </div>
            <div class="comment-input">
                <input type="text" placeholder="댓글을 입력해주세요" name='comment_input'>
            </div>
        </div>
        <div class="comment-content">
            {% for data in comment %}
                <div class="comment-box">
                    <div class="user-profile-img">
                        {% if data.writer.profile_image %}
                            <img src="{{data.writer.profile_image.url}}"  class="img-profile rounded-circle" style= "width: 2rem; height: 2rem;"alt="">
                        {% else %}
                            <img src="" alt="">
                        {% endif %}
                        <div class="user-info">
                            <div class="user-name">
                                {{data.writer.username}}님
                            </div>
                            <div class="date">
                                {{data.create_at|timesince:current_time}}
                            </div>
                        </div>
                    </div>
                    <div class="user-comment">
                        
                        <div class="user-comment-content">
                            {{data.content}}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <script>
        var postPk = "{{post.id}}";
        const input = document.querySelector('input[name="comment_input"]');
        
        
        input.addEventListener('keyup', e =>{
            console.log(e);
            if (e.keyCode === 13){
                addComment(e);
            }
        })

        function addComment(e){
            let value = input.value;
            var csrf_token = document.getElementsByName('csrfmiddlewaretoken')[0].value;
            console.log(value);

            let formData = new FormData();
            formData.append('content', value);

            let resp = fetch('/board/add_comment/'+ postPk, {
                method: "POST",
                headers: {
                    'X-CSRFToken': csrf_token,  // CSRF 토큰 설정
                },
                body:formData,
            })
            .then(resp => resp.json())
            .then(data =>{
                document.location.reload();
                console.log(data)
                input.value = '';
            })
        }
    </script>
</div>

final/board/templates/boards/post_test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="manifest" href="site.webmanifest">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'boards/post.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin_vendor/fontawesome-free/css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/chatbot.css' %}">
</head>
<body>

    {% include 'nav.html' %}
    {% include 'boards/post_detail.html' %}
    {% comment %} {% include '..\..\..\final\trip\templates\footer.html'%} {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
	<!-- JS here -->
	
		<!-- All JS Custom Plugins Link Here here -->
        <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
		
		<!-- Jquery, Popper, Bootstrap -->
		<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
	    <!-- Jquery Mobile Menu -->
        <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>

		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/slick.min.js' %}"></script>
		<!-- One Page, Animated-HeadLin -->
        <script src="{% static 'js/wow.min.js' %}"></script>
		<script src="{% static 'js/animated.headline.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

		<!-- Scrollup, nice-select, sticky -->
        <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
		<script src="{% static 'js/jquery.sticky.js' %}"></script>
        
        <!-- contact js -->
        <script src="{% static 'js/contact.js' %}"></script>
        <script src="{% static 'js/jquery.form.js' %}"></script>
        <script src="{% static 'js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        
		<!-- Jquery Plugins, main Jquery -->	
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

        <!-- ChatBot -->
        <script src="{% static 'js/chatbot.js' %}"></script>
</body>
</html>

final/board/templates/boards/write.html
{% comment %} {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'boards/write.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="form-container">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="card">
                <div class="card-header">
                    {{ form.title }}
                </div>
                <div>
                    {{ form.content }}
                </div>
            </div>
        
            <div class="text-right">   
                <button type="submit" id="write" class="btn btn-sm">작성하기</button>
            </div>
        </form>
    </div>
</body>
</html> {% endcomment %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="manifest" href="site.webmanifest">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'boards/board.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin_vendor/fontawesome-free/css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/chatbot.css' %}">

    <link rel="stylesheet" href="{% static 'boards/write.css' %}">
</head>
<body>
    {% include 'nav.html' %}
    <div class="form-container">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="card">
                <div class="card-header">
                    {{ form.title }}
                </div>
                <div>
                    {{ form.content }}
                </div>
            </div>
        
            <div class="text-right">   
                <button type="submit" id="write" class="btn btn-sm">작성하기</button>
            </div>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
	<!-- JS here -->
	
		<!-- All JS Custom Plugins Link Here here -->
        <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
		
		<!-- Jquery, Popper, Bootstrap -->
		<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
	    <!-- Jquery Mobile Menu -->
        <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>

		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/slick.min.js' %}"></script>
		<!-- One Page, Animated-HeadLin -->
        <script src="{% static 'js/wow.min.js' %}"></script>
		<script src="{% static 'js/animated.headline.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

		<!-- Scrollup, nice-select, sticky -->
        <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
		<script src="{% static 'js/jquery.sticky.js' %}"></script>
        
        <!-- contact js -->
        <script src="{% static 'js/contact.js' %}"></script>
        <script src="{% static 'js/jquery.form.js' %}"></script>
        <script src="{% static 'js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        
		<!-- Jquery Plugins, main Jquery -->	
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

        <!-- ChatBot -->
        <script src="{% static 'js/chatbot.js' %}"></script>
</body>
</html>