final/board/urls.py
from django.urls import path
from . import views

app_name ='board'

urlpatterns = [
    path('', views.BoardListView.as_view(), name='board_list'),
    path('post/<int:pk>/', views.post_detail_view, name='post_detail'),
    path('write/', views.post_write_view, name='post_write'),
    path('add_comment/<int:pk>', views.post_comment_add_view, name='add_comment')
]

final/final/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("trip.urls")),
    path('board/', include('board.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/trip_app/favicon.ico', permanent=True)),
    path('summernote/', include('django_summernote.urls')),
    path('', include('social_django.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/trip/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'trip'
urlpatterns = [

    # 메인페이지 by 영환
    path('search_trip/', views.search_trip, name='search_trip'),
    
    # 메인페이지 종료

    # 마이페이지 by 영환
    path('mypage/profile/', views.profile, name='profile'),
    path('mypage/post_detail/<int:post_id>', views.post_detail, name='post_detail'),
    path('mypage/mytopics/', views.mytopics, name='mytopics'),
    path('mypage/myfeadback/', views.myfeadback, name='myfeadback'),
    path('mypage/like_schedule/', views.like_schedule, name='like_schedule'),
    path('mypage/chatting_room/', views.chatting_room, name='chatting_room'),
    path('mypage/user_report/', views.user_report, name='user_report'),
    path('mypage/report_submit/', views.report_submit, name='report_submit'),
    path('mypage/view_report/', views.view_report, name='view_report'),
    path('mypage/view_user_report/<int:id>', views.view_user_report, name='view_user_report'),
    path('mypage/report_update/<int:id>', views.report_update, name='report_update'),
    
    # 관리자 페이지 by 영환
    path("admin_page/", views.admin_page, name="admin_page"),
    path("admin_page/admin_management", views.admin_management, name="admin_management"),
    path("admin_page/change_state/<str:username>", views.change_state, name="change_state"),
    path("admin_page/create_product", views.create_product, name="create_product"),
    path("admin_page/update_product/<int:package_id>", views.update_product, name="update_product"),
    path("admin_page/product_management", views.product_management, name="product_management"),
    path("admin_page/deleted_product", views.deleted_product, name="deleted_product"),
    path("admin_page/delete_cancel/<int:package_id>", views.delete_cancel, name="delete_cancel"),
    path("admin_page/order_inquiry", views.order_inquiry, name="order_inquiry"),
    path("admin_page/delivery_tracking", views.delivery_tracking, name="delivery_tracking"),
    path("admin_page/return_management", views.return_management, name="return_management"),
    path("admin_page/report_detail", views.report_detail, name="report_detail"),
    path("admin_page/view_report_detail/<int:id>", views.view_report_detail, name="view_report_detail"),
    path("admin_page/report_complete/<int:id>", views.report_complete, name="report_complete"),
    path("admin_page/blacklist_management", views.blacklist_management, name="blacklist_management"),
    path("admin_page/black_cancel/<int:blacklist_id>", views.black_cancel, name="black_cancel"),
    # 관리자 페이지 종료

    #by 건영
    path('',views.index, name = "index"),
    path('about/',views.about, name='about'),
    path('contact/',views.contact, name='contact'),
    path('elements/',views.elements, name='elements'),
    path('main/',views.main, name='main'),
    path('together_walk/',views.together_walk, name='together_walk'),
    path('add_comment/<int:id>/', views.add_comment, name='add_comment'),
    path('delete_comment/<int:id>/', views.delete_comment, name='delete_comment'),
  
    # 여행 상품 페이지 By 수현
    path('packages/',views.packages, name='packages'),
    path('packages/package_detail/<int:id>',views.package_detail, name='package_detail'),
    path('together_detail/<int:id>/',views.together_detail, name='together_detail'), 
    path('together_detail/',views.together_detail, name='together_detail'),

    # 위시리스트 추가 by 문정
    path('add_wishlist/<int:id>', views.add_wishlist, name='add_wishlist'),

    # 로그인, 회원가입 페이지 by 문정
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name= 'logout'),
    path('register/', views.register, name='register'),
    
    #CHATBOT BY 영민
    path('chatbot/', views.chatbot, name='chatbot'),
    path('chatapi/<str:question>', views.chatapi, name='chatapi'),
    
    #실시간 채팅 BY 영민
    path('chat/', views.chatting, name='chatting'),
    path('chat/<str:room_name>/', views.room, name='room'),
    path('test/', views.chat_test, name="chat_test"),
    path('check_room/<int:room_name>/<str:room_title>', views.check_room, name='check_room'),
    path('room_list', views.room_list, name='room_list'),

    #동행모집글 By 수현
    path('community/', views.community, name='community'),
    
    path('community_write/', views.community_write, name='community_write'),
    path('set_write/', views.set_write, name='set_write'),
    path('set_region/', views.set_region, name='set_region'),
    
    path('delete_write/', views.delete_write, name='delete_write'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/trip/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
# from .forms import CommentForm

from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from .models import Package, User, Report,Schedule,ScheduleComment, Community, TogetherPost,TogetherComment, GroupChat, WishList
from django.contrib.auth.decorators import login_required
import openai
from django.http import JsonResponse
import json
from django.contrib import messages
from .forms import UserForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.http import JsonResponse
from .forms import UserProfileForm, CommentForm
from django.contrib.auth import update_session_auth_hash
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage

from .serializer import GroupChatSerializer
# Create your views here.

# 메인페이지 시작 By 영환

def search_trip(request):

    if request.method == "POST":
        action = request.POST.get('action')
        if action == 'search':
            search_region = request.POST['region']
            posts = TogetherPost.objects.filter(region=search_region)
        context = {
            "search_region" : search_region,
            "posts" : posts
        }
    return render(request, 'together_walk.html',context)

# 메인페이지 종료

# 마이페이지 시작 By 영환
@login_required
def profile(request): #내 정보 수정
    user = request.user
    form = UserProfileForm(initial={'username': user.username})
    user_info = get_object_or_404(User, username=user.username)
    print(user_info.profile_image)

    if request.method == 'POST' and user_info.profile_image == "":
        user_info.profile_image = request.FILES['profile_img']
        user_info.save()
        return redirect('trip:profile')
    
    if request.method == 'POST' and user_info.profile_image != "":
        form = UserProfileForm(request.POST)
        if 'profile_img' in request.FILES:
            user_info.profile_image = request.FILES['profile_img']
            user_info.save()

            context = {
                "form" : form,
                "user_info" : user_info
            }
            return redirect('trip:profile')

        if form.is_valid():
            nickname = form.cleaned_data['nickname']
            password = form.cleaned_data['password']
            password_confirm = form.cleaned_data['password_confirm']

            if nickname != user.nickname:
                user.nickname = nickname
                user.save()
                messages.success(request, '닉네임이 업데이트되었습니다.')

            if password:
                if password == password_confirm:
                    
                    user.set_password(password)
                    user.save()
                    update_session_auth_hash(request, user)
                    messages.success(request, '비밀번호가 업데이트되었습니다.')
                else:
                    messages.error(request, '비밀번호와 비밀번호 확인이 일치하지 않습니다.')
            context = {
                "form" : form,
                "user_info" : user_info
            }
            return redirect('trip:profile')

    context = {
        "form" : form,
        "user_info" : user_info
    }

    return render(request, 'mypage/profile.html', context)

@login_required
def mytopics(request):#내가 쓴 글 보기
    
    login_username = request.user.username
    login_user = get_object_or_404(User, username=login_username)

    my_posts = TogetherPost.objects.filter(user_id_id=login_user.id)

    context = {
        "my_posts" : my_posts
    }

    return render(request, 'mypage/mytopics.html', context)

@login_required
def myfeadback(request): #내가받은 후기 보기
    return render(request,'mypage/myfeadback.html')

@login_required
def like_schedule(request): #찜한 일정 리스트
    user_id   = request.user.id
    wish_list = WishList.objects.filter(user_id_id=user_id)
    package_list = []

    for i in range(0, len(wish_list)):
        package = get_object_or_404(Package, id=wish_list[i].product_id)
        package_list.append(package)
    
    context = {
        'items' : package_list
    }
    return render(request,'mypage/like_schedule.html', context)
    # return render(request,'mypage/like_test.html')


@login_required
def add_wishlist(request,id): # 위시리스트 추가
    user_id = request.user.id

    if not WishList.objects.filter(user_id_id = user_id, product_id = id).exists():
        add_wishlist = WishList(user_id_id = user_id,product_id = id,created_at = timezone.now())
        add_wishlist.save()

        # wish_list = WishList.objects.filter(user_id_id=user_id)
        # package_list = []

        # for i in range(0, len(wish_list)):
        #     package = get_object_or_404(Package, id=wish_list[i].product_id)
        #     package_list.append(package)
        
        # context = {
        #     'package' : package_list
        # }
    
    else:
        WishList.objects.get(user_id_id = user_id, product_id = id).delete()
        return redirect("trip:package_detail", id)
    return redirect("trip:package_detail", id)
    # return render (request, "mypage/like_schedule.html",context)


@login_required
def chatting_room(request): #채팅방리스트
    return render(request,'mypage/chatting_room.html')

@login_required
def user_report(request):
    return render(request, 'mypage/user_report.html')

@login_required
def report_submit(request):
    report = Report()
    if request.method == "POST":
        report.user_id_id = request.user.id
        report.reported_user = request.POST['reported_user']
        report.report_reason = request.POST['report_content']
        report.save()

    return redirect('trip:view_report')

@login_required
def view_report(request):
    report_list = Report.objects.filter(user_id_id=request.user.id, is_deleted=False)
    context = {
        "report_list" : report_list
    }
    return render(request, "mypage/view_report.html", context)

@login_required
def view_user_report(request, id) :
    report_detail = get_object_or_404(Report, id=id)
    context = {
        "report_detail" : report_detail
    }
    return render(request, "mypage/view_user_report.html", context)

@login_required
def report_update(request, id):
    report = get_object_or_404(Report, id=id)
    if request.method == "POST":
        action = request.POST.get('action')
        if action == 'update':
            report.report_reason = request.POST['report_content']
            print(report.report_reason)
            report.save()

        elif action == 'delete':
            report.is_deleted = True
            report.save()

    return redirect('trip:view_report')

# 마이페이지 종료

def post_detail(request, post_id):
    return render(request, 'post_detail.html')

# 관리자페이지 시작 by 영환

@login_required
def admin_check(request):
    if request.user.is_authenticated:
        user = request.user.username
        user_info = get_object_or_404(User, username=user)
        if user_info.is_staff == True :
            return True
        else:
            return False
        
@login_required
def admin_page(request):

    if admin_check(request) == True :
        return render(request,"admin/admin_page.html")
    else:
        return render(request, "index.html")

def admin_management(request):

    if admin_check(request) == True :
        user_list = User.objects.all().order_by('-is_staff')
        context = {
            'user_list' : user_list
        }

        return render(request, "admin/admin_management.html", context)
    else:
        return render(request, "index.html")

@login_required
def change_state(request, username):
    
    if admin_check(request) == True :
        if request.method == "POST":
            user = get_object_or_404(User, username=username)
            action = request.POST.get('action')
        if action == 'to_user':
            user.is_staff = False
            user.save()
        elif action == 'to_admin':
            user.is_staff = True
            user.save()

        user_list = User.objects.all().order_by('-is_staff')
        context = {
            'user_list' : user_list
        }
        return render(request, "admin/admin_management.html", context)
    else:
        return render(request, "main.html")

@login_required 
def create_product(request):

    if admin_check(request) == True :
        package = Package()
        if request.method == "POST":
            package.title = request.POST['title']
            package.price = request.POST['price']
            package.destination = request.POST['destination']
            package.start_date = request.POST['start_date']
            package.end_date = request.POST['end_date']
            package.content = request.POST['content']
            package.post_author_id = request.user.id
            if 'package_image' in request.FILES:
                package.image = request.FILES['package_image']
            package.save()
            return redirect('trip:product_management')

        return render(request, "admin/create_product.html")
    else :
        return redirect("trip:main")

@login_required
def update_product(request, package_id):

    if admin_check(request) == True :
        package = get_object_or_404(Package, id=package_id)
        if package:
            package.content = package.content.strip()
        
        if request.method == "POST":
            action = request.POST.get('action')
            if action == 'update':
                package.title = request.POST['title']
                package.price = request.POST['price']
                package.destination = request.POST['destination']
                package.start_date = request.POST['start_date']
                package.end_date = request.POST['end_date']
                package.content = request.POST['content']
                if 'package_image' in request.FILES:
                    package.image = request.FILES['package_image']
                package.save()

final/trip/templates/blog.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Travel HTML-5 Template </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <!-- Place favicon.ico in the root directory -->
    
  <!-- CSS here -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'css/slick.css' %}">
  <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>

<body>
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'img/logo/logo.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start-->
    <header>
        <!-- Header Start -->
        {% include "nav.html" %}
        <!-- Header End -->
    </header>
  
     <!-- slider Area Start-->
     <div class="slider-area ">
        <!-- Mobile Menu -->
        <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'img/blog_images.jpeg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <form method="POST" action="{% url 'trip:search_trip' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <div class="col-xl-9 col-lg-9 col-md-9">
                                        <div class="hero__caption">
                                            <h1>동행을 구해볼까요?</h1>
                                            <p>가고 싶은 지역을 검색해서 동행을 찾아보세요!</p>
                                            {% if search_region %}
                                                <div style="display: flex; flex-direction: row; justify-content: space-between;">
                                                    <input type="text" class="form-control custom-input" value="{{search_region}}" name="region"
                                                    onfocus="this.placeholder = '{{search_region}}'"
                                                    onblur="this.placeholder = '{{search_region}}'">
                                                    <button class="btns" type="submit" value="search" name="action"><i class="ti-search"></i></button>
                                                </div>
                                            {% else %}
                                                <div style="display: flex; flex-direction: row; justify-content: space-between;">
                                                    <input type="text" class="form-control custom-input" placeholder='어디로 떠나시나요?' name="region"
                                                        onfocus="this.placeholder = ''"
                                                        onblur="this.placeholder = '어디로 떠나시나요?'">
                                                    <button class="btns" type="submit" value="search" name="action"><i class="ti-search"></i></button>
                                                </div>
                                            {% endif %}
                                            
                                        </div>
                                    </div>

                                    
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
     </div>
     <!-- slider Area End-->
    <!--================Blog Area =================-->
    <section class="blog_area section-padding" style="display: flex; flex-wrap: nowrap; overflow-x: auto;">
        <div class="container" style="justify-content:center; align-items:center;">
            <div style="max-width: 1500px;">
                <div>
                    {% if posts%}
                        {% for post in posts %}
                            <article class="blog_item" style="max-width: 20%;">
                                <div class="blog_item_img">

                                    {% if post.post_image %}
                                    <img class="card-img rounded-0" src="{{ post.post_image.url }}" alt="{{ post.post_title }}">
                                    {% endif %}
                                </div> 

                                <div class="blog_details" style="margin: 0 auto;">
                                    <a class="d-inline-block" href="{% url 'trip:together_detail' post.id %}">
                                        <h2 style="font-size: 18px;">{{ post.post_title|truncatechars:12 }}</h2>
                                    </a>
                                    <p style="font-size: 14px;">{{ post.post_content|truncatechars:15 }}</p>
                                    <p class="dolor">{{ post.recuited_people }}<span>명 모집중 / {{ post.region }}</span></p>
                                    <ul>
                                        <li style="font-size:14px;"><span>여행기간</span></li>
                                    <li style="font-size:14px;"><i class="far fa-clock"> <span> </span> {{ post.start_date|date:"m/d/Y" }}<span> ~ </span>{{ post.end_date|date:"m/d/Y" }}</i></li>
                                    </ul>
                                    <ul class="blog-info-link">
                                        <li style="margin-right: 10px; width:30px; height:30px;"><img class="img-profile rounded-circle" src="{% static 'img/undraw_profile.svg' %}"></li>
                                        <li style="font-size: 14px;">{{ post.user_id }}</li>
                                    </ul>
                                </div>
                            </article>
                        {% endfor %}
                    {% else %}
                        <div class="no-search-result" style="height: 20rem;"> 조회된 결과가 없습니다.<br>지역명으로 검색해주세요.</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
    <footer>
        <!-- Footer Start-->
        {% include "footer.html" %}
        <!-- Footer End-->
    </footer>

<!-- JS here -->
	
		<!-- All JS Custom Plugins Link Here here -->
        <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
		
		<!-- Jquery, Popper, Bootstrap -->
		<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
	    <!-- Jquery Mobile Menu -->
        <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>

		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/slick.min.js' %}"></script>

		<!-- One Page, Animated-HeadLin -->
        <script src="{% static 'js/wow.min.js' %}"></script>
		<script src="{% static 'js/animated.headline.js' %}"></script>
		
		<!-- Scrollup, nice-select, sticky -->
        <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
		<script src="{% static 'js/jquery.sticky.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

        <!-- contact js -->
        <script src="{% static 'js/contact.js' %}"></script>
        <script src="{% static 'js/jquery.form.js' %}"></script>
        <script src="{% static 'js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        
		<!-- Jquery Plugins, main Jquery -->	
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

final/trip/templates/chatbot.html
{% load static %}
<div class='bottom-right fixed open-modal-box shadow' id="open-modal">
    <i class="fa-solid fa-robot fa-2x"></i>
</div>
<div class='bottom-right fixed shadow' id = 'close-box'>
    X
</div>
<div id="chatbot-modal">
    <div class="flex-center modal-header">
        <h4 class="modal-h4">AI 챗봇 무엇이든 물어봐주세요</h4>
    </div>
    <div class="modal-content">
        <div class="answer-box">
            <div class="answer">
                무엇을 도와드릴까요?
            </div>
        </div>
    </div>
    <div class="modal-input-box">
        <input class="modal-input" type="text" id="modal-input" placeholder="여기에 궁금한 내용을 적어주세요">
    </div>
</div>
<script>
    const baseURL = "{% url 'trip:index' %}";
</script>

final/trip/templates/cmtest.html
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=7d5511716523c9fb7d55def390e73d6a&libraries=services"></script>
<div class="container" style='width:1000px;'>

</div>

<script>
    var resp = fetch('cmtest/')
        .then(resp => resp.json())
        .then(data => console.log(data))
</script>

final/trip/templates/footer.html
{% load static %}
<footer>
    <!-- Footer Start-->
    <div class="footer-area footer-padding footer-bg" data-background="{% static 'img/main_footer_image.jpg' %}">
        <div class="container">
            <div class="row d-flex justify-content-between">
                <div class="col-xl-8 col-lg-8 col-md-5 col-sm-6">
                   <div class="single-footer-caption mb-50">
                     <div class="single-footer-caption mb-30">
                          <!-- logo -->
                         <div class="footer-logo">
                             <a href="index.html"><img src="{% static 'img_m/logo/logo2_footer.png' %}" alt=""></a>
                         </div>
                         <div class="footer-tittle">
                             <div class="footer-pera">
                                 <p>전국의 다양한 사람들과 만나서 가는 여행! <br>본인과 비슷한 여행취향 및 취미를 가진 사람들과 즐거운 동행을 해보세요.</p>
                            </div>
                         </div>
                     </div>
                   </div>
                </div>
                <div class="col-xl-2 col-lg-3 col-md-3 col-sm-5">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Quick Links</h4>
                            <ul>
                                <li><a href="{% url 'trip:index' %}">홈</a></li>                                                                                                                                    
                                <li><a href="{% url 'trip:together_walk' %}">동행 구하기</a></li>
                                <li><a href="{% url 'trip:packages' %}">여행상품</a></li>
                                <li><a href="{% url 'trip:together_walk' %}">커뮤니티</a></li>
                                <li><a href="#">  Contact Us</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                
            </div>
            <!-- Footer bottom -->
            <div class="row pt-padding">
             <div class="col-xl-7 col-lg-7 col-md-7">
                <div class="footer-copy-right">
                    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script>만남은 쉽고 이별은 어렵조 <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
             </div>
         </div>
        </div>
    </div>
    <!-- Footer End-->
</footer>

final/trip/templates/nav.html
{% load static %}
<div class="header-area">
    <div class="main-header ">
        
       <div class="header-bottom  header-sticky">
            <div class="container">
                <div class="row align-items-center">
                    <!-- Logo -->
                    <div class="col-xl-2 col-lg-2 col-md-1">
                        <div class="logo">
                          <a href="{% url 'trip:index' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                        </div>
                    </div>
                    <div class="col-xl-10 col-lg-10 col-md-10">
                        <!-- Main-menu -->
                        <div class="main-menu f-right d-none d-lg-block">
                            <nav>               
                                <ul id="navigation">
                                    <li><a href="{% url 'trip:index' %}">홈</a></li>                                                                                                                                    
                                    <li><a href="{% url 'trip:blog' %}">동행 구하기</a></li>
                                    <li><a href="{% url 'trip:packages' %}">여행상품</a></li>
                                    <li><a href="{% url 'board:board_list' %}">커뮤니티</a></li>
                                    <!-- 로그인/로그아웃 버튼 -->
                                    {% if user.is_authenticated %}
                                        {% if user.is_staff %}
                                        <li><a href="{% url 'trip:admin_page' %}">관리자페이지</a></li>
                                        {% endif %}
                                        <li><a href="{% url 'trip:logout' %}">로그아웃</a></li>
                                    {% else %}
                                        <li><a href="{% url 'trip:login' %}">로그인</a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
       </div>
    </div>
</div>

final/trip/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

final/trip/templates/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/chatbot.css' %}">
    <title>Document</title>
</head>
<body>
    {% include "chatbot.html" %}
</body>
<script src="{% static 'js/chatbot.js' %}"></script>
</html>