final/board/urls.py
from django.urls import path
from . import views

app_name ='board'

urlpatterns = [
    path('', views.BoardListView.as_view(), name='board_list'),
    path('post/<int:pk>/', views.post_detail_view, name='post_detail'),
    path('write/', views.post_write_view, name='post_write'),
    path('add_comment/<int:pk>', views.post_comment_add_view, name='add_comment')
]

final/final/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("trip.urls")),
    path('board/', include('board.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/trip_app/favicon.ico', permanent=True)),
    path('summernote/', include('django_summernote.urls')),
    path('', include('social_django.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/trip/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'trip'
urlpatterns = [

    # 메인페이지 by 영환
    path('search_trip/', views.search_trip, name='search_trip'),
    
    # 메인페이지 종료

    # 마이페이지 by 영환
    path('mypage/profile/', views.profile, name='profile'),
    path('mypage/post_detail/<int:post_id>', views.post_detail, name='post_detail'),
    path('mypage/mytopics/', views.mytopics, name='mytopics'),
    path('mypage/myfeadback/', views.myfeadback, name='myfeadback'),
    path('mypage/like_schedule/', views.like_schedule, name='like_schedule'),
    path('mypage/chatting_room/', views.chatting_room, name='chatting_room'),
    path('mypage/user_report/', views.user_report, name='user_report'),
    path('mypage/report_submit/', views.report_submit, name='report_submit'),
    path('mypage/view_report/', views.view_report, name='view_report'),
    path('mypage/view_user_report/<int:id>', views.view_user_report, name='view_user_report'),
    path('mypage/report_update/<int:id>', views.report_update, name='report_update'),
    
    # 관리자 페이지 by 영환
    path("admin_page/", views.admin_page, name="admin_page"),
    path("admin_page/admin_management", views.admin_management, name="admin_management"),
    path("admin_page/change_state/<str:username>", views.change_state, name="change_state"),
    path("admin_page/create_product", views.create_product, name="create_product"),
    path("admin_page/update_product/<int:package_id>", views.update_product, name="update_product"),
    path("admin_page/product_management", views.product_management, name="product_management"),
    path("admin_page/deleted_product", views.deleted_product, name="deleted_product"),
    path("admin_page/delete_cancel/<int:package_id>", views.delete_cancel, name="delete_cancel"),
    path("admin_page/order_inquiry", views.order_inquiry, name="order_inquiry"),
    path("admin_page/delivery_tracking", views.delivery_tracking, name="delivery_tracking"),
    path("admin_page/return_management", views.return_management, name="return_management"),
    path("admin_page/report_detail", views.report_detail, name="report_detail"),
    path("admin_page/view_report_detail/<int:id>", views.view_report_detail, name="view_report_detail"),
    path("admin_page/report_complete/<int:id>", views.report_complete, name="report_complete"),
    path("admin_page/blacklist_management", views.blacklist_management, name="blacklist_management"),
    path("admin_page/black_cancel/<int:blacklist_id>", views.black_cancel, name="black_cancel"),
    # 관리자 페이지 종료

    #by 건영
    path('',views.index, name = "index"),
    path('about/',views.about, name='about'),
    path('contact/',views.contact, name='contact'),
    path('elements/',views.elements, name='elements'),
    path('main/',views.main, name='main'),
    path('together_walk/',views.together_walk, name='together_walk'),
    path('add_comment/<int:id>/', views.add_comment, name='add_comment'),
    path('delete_comment/<int:id>/', views.delete_comment, name='delete_comment'),
  
    # 여행 상품 페이지 By 수현
    path('packages/',views.packages, name='packages'),
    path('packages/package_detail/<int:id>',views.package_detail, name='package_detail'),
    path('together_detail/<int:id>/',views.together_detail, name='together_detail'), 
    path('together_detail/',views.together_detail, name='together_detail'),

    # 위시리스트 추가 by 문정
    path('add_wishlist/<int:id>', views.add_wishlist, name='add_wishlist'),

    # 로그인, 회원가입 페이지 by 문정
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name= 'logout'),
    path('register/', views.register, name='register'),
    
    #CHATBOT BY 영민
    path('chatbot/', views.chatbot, name='chatbot'),
    path('chatapi/<str:question>', views.chatapi, name='chatapi'),
    
    #실시간 채팅 BY 영민
    path('chat/', views.chatting, name='chatting'),
    path('chat/<str:room_name>/', views.room, name='room'),
    path('test/', views.chat_test, name="chat_test"),
    path('check_room/<int:room_name>/<str:room_title>', views.check_room, name='check_room'),
    path('room_list', views.room_list, name='room_list'),

    #동행모집글 By 수현
    path('community/', views.community, name='community'),
    
    path('community_write/', views.community_write, name='community_write'),
    path('set_write/', views.set_write, name='set_write'),
    path('set_region/', views.set_region, name='set_region'),
    
    path('delete_write/', views.delete_write, name='delete_write'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/trip/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
# from .forms import CommentForm

from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from .models import Package, User, Report,Schedule,ScheduleComment, Community, TogetherPost,TogetherComment, GroupChat, WishList
from django.contrib.auth.decorators import login_required
import openai
from django.http import JsonResponse
import json
from django.contrib import messages
from .forms import UserForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.http import JsonResponse
from .forms import UserProfileForm, CommentForm
from django.contrib.auth import update_session_auth_hash
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage

from .serializer import GroupChatSerializer
# Create your views here.

# 메인페이지 시작 By 영환

def search_trip(request):

    if request.method == "POST":
        action = request.POST.get('action')
        if action == 'search':
            search_region = request.POST['region']
            posts = TogetherPost.objects.filter(region=search_region)
        context = {
            "search_region" : search_region,
            "posts" : posts
        }
    return render(request, 'together_walk.html',context)

# 메인페이지 종료

# 마이페이지 시작 By 영환
@login_required
def profile(request): #내 정보 수정
    user = request.user
    form = UserProfileForm(initial={'username': user.username})
    user_info = get_object_or_404(User, username=user.username)
    print(user_info.profile_image)

    if request.method == 'POST' and user_info.profile_image == "":
        user_info.profile_image = request.FILES['profile_img']
        user_info.save()
        return redirect('trip:profile')
    
    if request.method == 'POST' and user_info.profile_image != "":
        form = UserProfileForm(request.POST)
        if 'profile_img' in request.FILES:
            user_info.profile_image = request.FILES['profile_img']
            user_info.save()

            context = {
                "form" : form,
                "user_info" : user_info
            }
            return redirect('trip:profile')

        if form.is_valid():
            nickname = form.cleaned_data['nickname']
            password = form.cleaned_data['password']
            password_confirm = form.cleaned_data['password_confirm']

            if nickname != user.nickname:
                user.nickname = nickname
                user.save()
                messages.success(request, '닉네임이 업데이트되었습니다.')

            if password:
                if password == password_confirm:
                    
                    user.set_password(password)
                    user.save()
                    update_session_auth_hash(request, user)
                    messages.success(request, '비밀번호가 업데이트되었습니다.')
                else:
                    messages.error(request, '비밀번호와 비밀번호 확인이 일치하지 않습니다.')
            context = {
                "form" : form,
                "user_info" : user_info
            }
            return redirect('trip:profile')

    context = {
        "form" : form,
        "user_info" : user_info
    }

    return render(request, 'mypage/profile.html', context)

@login_required
def mytopics(request):#내가 쓴 글 보기
    
    login_username = request.user.username
    login_user = get_object_or_404(User, username=login_username)

    my_posts = TogetherPost.objects.filter(user_id_id=login_user.id)

    context = {
        "my_posts" : my_posts
    }

    return render(request, 'mypage/mytopics.html', context)

@login_required
def myfeadback(request): #내가받은 후기 보기
    return render(request,'mypage/myfeadback.html')

@login_required
def like_schedule(request): #찜한 일정 리스트
    user_id   = request.user.id
    wish_list = WishList.objects.filter(user_id_id=user_id)
    package_list = []

    for i in range(0, len(wish_list)):
        package = get_object_or_404(Package, id=wish_list[i].product_id)
        package_list.append(package)
    
    context = {
        'items' : package_list
    }
    return render(request,'mypage/like_schedule.html', context)
    # return render(request,'mypage/like_test.html')


@login_required
def add_wishlist(request,id): # 위시리스트 추가
    user_id = request.user.id

    if not WishList.objects.filter(user_id_id = user_id, product_id = id).exists():
        add_wishlist = WishList(user_id_id = user_id,product_id = id,created_at = timezone.now())
        add_wishlist.save()

        # wish_list = WishList.objects.filter(user_id_id=user_id)
        # package_list = []

        # for i in range(0, len(wish_list)):
        #     package = get_object_or_404(Package, id=wish_list[i].product_id)
        #     package_list.append(package)
        
        # context = {
        #     'package' : package_list
        # }
    
    else:
        WishList.objects.get(user_id_id = user_id, product_id = id).delete()
        return redirect("trip:package_detail", id)
    return redirect("trip:package_detail", id)
    # return render (request, "mypage/like_schedule.html",context)


@login_required
def chatting_room(request): #채팅방리스트
    return render(request,'mypage/chatting_room.html')

@login_required
def user_report(request):
    return render(request, 'mypage/user_report.html')

@login_required
def report_submit(request):
    report = Report()
    if request.method == "POST":
        report.user_id_id = request.user.id
        report.reported_user = request.POST['reported_user']
        report.report_reason = request.POST['report_content']
        report.save()

    return redirect('trip:view_report')

@login_required
def view_report(request):
    report_list = Report.objects.filter(user_id_id=request.user.id, is_deleted=False)
    context = {
        "report_list" : report_list
    }
    return render(request, "mypage/view_report.html", context)

@login_required
def view_user_report(request, id) :
    report_detail = get_object_or_404(Report, id=id)
    context = {
        "report_detail" : report_detail
    }
    return render(request, "mypage/view_user_report.html", context)

@login_required
def report_update(request, id):
    report = get_object_or_404(Report, id=id)
    if request.method == "POST":
        action = request.POST.get('action')
        if action == 'update':
            report.report_reason = request.POST['report_content']
            print(report.report_reason)
            report.save()

        elif action == 'delete':
            report.is_deleted = True
            report.save()

    return redirect('trip:view_report')

# 마이페이지 종료

def post_detail(request, post_id):
    return render(request, 'post_detail.html')

# 관리자페이지 시작 by 영환

@login_required
def admin_check(request):
    if request.user.is_authenticated:
        user = request.user.username
        user_info = get_object_or_404(User, username=user)
        if user_info.is_staff == True :
            return True
        else:
            return False
        
@login_required
def admin_page(request):

    if admin_check(request) == True :
        return render(request,"admin/admin_page.html")
    else:
        return render(request, "index.html")

def admin_management(request):

    if admin_check(request) == True :
        user_list = User.objects.all().order_by('-is_staff')
        context = {
            'user_list' : user_list
        }

        return render(request, "admin/admin_management.html", context)
    else:
        return render(request, "index.html")

@login_required
def change_state(request, username):
    
    if admin_check(request) == True :
        if request.method == "POST":
            user = get_object_or_404(User, username=username)
            action = request.POST.get('action')
        if action == 'to_user':
            user.is_staff = False
            user.save()
        elif action == 'to_admin':
            user.is_staff = True
            user.save()

        user_list = User.objects.all().order_by('-is_staff')
        context = {
            'user_list' : user_list
        }
        return render(request, "admin/admin_management.html", context)
    else:
        return render(request, "main.html")

@login_required 
def create_product(request):

    if admin_check(request) == True :
        package = Package()
        if request.method == "POST":
            package.title = request.POST['title']
            package.price = request.POST['price']
            package.destination = request.POST['destination']
            package.start_date = request.POST['start_date']
            package.end_date = request.POST['end_date']
            package.content = request.POST['content']
            package.post_author_id = request.user.id
            if 'package_image' in request.FILES:
                package.image = request.FILES['package_image']
            package.save()
            return redirect('trip:product_management')

        return render(request, "admin/create_product.html")
    else :
        return redirect("trip:main")

@login_required
def update_product(request, package_id):

    if admin_check(request) == True :
        package = get_object_or_404(Package, id=package_id)
        if package:
            package.content = package.content.strip()
        
        if request.method == "POST":
            action = request.POST.get('action')
            if action == 'update':
                package.title = request.POST['title']
                package.price = request.POST['price']
                package.destination = request.POST['destination']
                package.start_date = request.POST['start_date']
                package.end_date = request.POST['end_date']
                package.content = request.POST['content']
                if 'package_image' in request.FILES:
                    package.image = request.FILES['package_image']
                package.save()

final/trip/templates/mypage/my_footer.html
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
      <div class="copyright text-center my-auto">
        <span>Copyright &copy; 만남은 쉽고 이별은 어렵조 2023</span>
      </div>
    </div>
  </footer>
  <!-- End of Footer -->

final/trip/templates/mypage/my_header.html
{% load static%}
<header>
    <!-- Header Start -->
    <div class="header-area">
      <div class="main-header">
        <div class="header-bottom header-sticky">
          <div class="container">
            <div class="row align-items-center">
              <!-- Logo -->
              <div class="col-xl-2 col-lg-2 col-md-1">
                <div class="logo">
                  <a href="{%url 'trip:index'%}"
                    ><img src="{% static 'img_m/logo/logo.png' %}" alt=""
                  /></a>
                </div>
              </div>
              <div class="col-xl-10 col-lg-10 col-md-10">
                <!-- Main-menu -->
                <div class="main-menu f-right d-none d-lg-block">
                  <nav>
                    <ul id="navigation">
                      <li><a href="{% url 'trip:index' %}">홈</a></li>                                                                                                                                    
                      <li><a href="{% url 'trip:blog' %}">동행 구하기</a></li>
                      <li><a href="{% url 'trip:packages' %}">여행상품</a></li>
                      <li><a href="{% url 'board:board_list' %}">커뮤니티</a></li>
                      <!-- 로그인/로그아웃 버튼 -->
                      {% if user.is_authenticated %}
                          {% if user.is_staff %}
                              <li><a href="{% url 'trip:admin_page' %}">관리자페이지</a></li>
                              <li><a href="{% url 'trip:logout' %}">로그아웃</a></li>
                          {%else %}
                              <li><a href="{% url 'trip:profile' %}">마이페이지</a></li>
                              <li><a href="{% url 'trip:community_write' %}">동행 글작성</a></li>
                              <li><a href="{% url 'trip:logout' %}">로그아웃</a></li>

                          {% endif %}
                          <li><a href="{% url 'trip:logout' %}">로그아웃</a></li>
                      {% else %}
                          <li><a href="{% url 'trip:login' %}">로그인</a></li>
                      {% endif %}
                  </ul>
                  </nav>
                </div>
              </div>
              <!-- Mobile Menu -->
              <div class="col-12">
                <div class="mobile_menu d-block d-lg-none"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Header End -->
</header>

final/trip/templates/mypage/my_sidebar.html
<!-- Sidebar -->
<ul
class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
id="accordionSidebar"
>
<!-- Sidebar - Brand -->
<a
  class="sidebar-brand d-flex align-items-center justify-content-center"
  href="{% url 'trip:index' %}"
  style="background-color: #ffc107"
>
  <div class="sidebar-brand-icon rotate-n-15">
    <i class="fas fa fa-plane"></i>
  </div>
  <div class="sidebar-brand-text mx-3">페이지 바로가기</div>
</a>
<!-- Nav Item - Dashboard -->
<li class="nav-item active">
  <a class="nav-link" href="{% url 'trip:profile' %}">
    <i class="fas fa-fw fa fa-user"></i>
    <span>내 정보 수정</span></a
  >
  <a class="nav-link" href="{% url 'trip:mytopics' %}">
    <i class="fas fa-fw fa fa-file"></i>
    <span>내 작성글 보기</span></a
  >
  <a class="nav-link" href="{% url 'trip:myfeadback' %}">
    <i class="fas fa-fw fa fa-envelope"></i>
    <span>내가 받은 동행 후기</span></a
  >
  <a class="nav-link" href="{% url 'trip:like_schedule' %}">
    <i class="fas fa-fw fa fa-suitcase"></i>
    <span>찜한 일정 리스트</span></a
  >
  <a class="nav-link" href="{% url 'trip:user_report' %}">
    <i class="fas fa-fw fa fa-bullhorn"></i>
    <span>사용자 신고하기</span></a
  >
  <a class="nav-link" href="{% url 'trip:view_report' %}">
    <i class="fas fa-fw fa fa-list-alt"></i>
    <span>신고내역 확인하기</span></a
  >
</li>

<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block" />

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
  <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>
</ul>
<!-- End of Sidebar -->

final/trip/templates/mypage/my_topbar.html
{% load static%}

<link rel="stylesheet" href="{% static 'css/chatbot.css' %}">

<!-- Topbar -->
<nav
class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
>
<!-- Sidebar Toggle (Topbar) -->
<button
  id="sidebarToggleTop"
  class="btn btn-link d-md-none rounded-circle mr-3"
>
  <i class="fa fa-bars"></i>
</button>

<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">
  <!-- Nav Item - Search Dropdown (Visible Only XS) -->
  <li class="nav-item dropdown no-arrow d-sm-none">
    <a
      class="nav-link dropdown-toggle"
      href="#"
      id="searchDropdown"
      role="button"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false"
    >
      <i class="fas fa-search fa-fw"></i>
    </a>
    <!-- Dropdown - Messages -->
    <div
      class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
      aria-labelledby="searchDropdown"
    >
      <form class="form-inline mr-auto w-100 navbar-search">
        <div class="input-group">
          <input
            type="text"
            class="form-control bg-light border-0 small"
            placeholder="Search for..."
            aria-label="Search"
            aria-describedby="basic-addon2"
          />
          <div class="input-group-append">
            <button class="btn btn-primary" type="button">
              <i class="fas fa-search fa-sm"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
  </li>
  <!-- Nav Item - User Information -->
  <li class="nav-item dropdown no-arrow">
    <a
      class="nav-link dropdown-toggle"
      href="#"
      id="userDropdown"
      role="button"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false"
    >
      <span class="mr-2 d-none d-lg-inline text-gray-600 small">
        {% if user.is_authenticated %}
        {{user.nickname}}님
        {% endif %}
      </span>
      {% if user.profile_image %}
        <img src = "{{user.profile_image.url}}" class="img-profile rounded-circle" alt="..."/>
      {% else %}
      <img src="{% static 'img/oreumi.jpg' %}" class="img-profile rounded-circle" alt="..."/>
      {% endif %}
    </a>
    <!-- Dropdown - User Information -->
    <div
      class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
      aria-labelledby="userDropdown"
    >
      <a
        class="dropdown-item"
        href="#"
        data-toggle="modal"
        data-target="#logoutModal"
      >
        <i
          class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"
        ></i>
        로그아웃
      </a>
    </div>
  </li>
</ul>
</nav>
<!-- End of Topbar -->

<!-- Logout Modal-->
<div
class="modal fade"
id="logoutModal"
tabindex="-1"
role="dialog"
aria-labelledby="exampleModalLabel"
aria-hidden="true"
>
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">로그아웃</h5>
      <button
        class="close"
        type="button"
        data-dismiss="modal"
        aria-label="Close"
      >
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      로그아웃 하시겠습니까?
    </div>
    <div class="modal-footer">
      <button
        class="btn btn-secondary"
        type="button"
        data-dismiss="modal"
      >
        취소
      </button>
      <a class="btn btn-primary" href="{% url 'trip:logout' %}">로그아웃</a>
    </div>
  </div>
</div>
</div>

{% include "chat/chat_merge.html" %}

<!-- ChatBot -->
<script src="{% static 'js/chatbot.js' %}"></script>